language: elixir

script:
  - mix format --check-formatted
  - mix credo --strict
  - travis_wait 30 mix dialyzer --halt-exit-status
  - mix coveralls.travis

matrix:
  include:
    - elixir: '1.8.1'
      otp_release: '21.3.8'
    - elixir: '1.9.2'
      otp_release: '22.0.4'
    - elixir: '1.10.2'
      otp_release: '22.0.4'

cache:
  directories:
    - _build
    - deps
